EMACS ?= emacs
ELISP = lisp/gptel-commit-msg.el
GPTEL_DIR ?= $(shell find "$(HOME)/.emacs.d" -type f -name gptel.el -print -quit 2>/dev/null | sed 's|/gptel\.el$$||')
LOAD_PATHS ?=
EMACS_LOAD_PATH_ARGS = $(if $(GPTEL_DIR),-L $(GPTEL_DIR)) $(foreach path,$(LOAD_PATHS),-L $(path))

.PHONY: help all check test compile clean

# Show this help.
help:
	@echo "Usage: make TARGET"
	@echo ""
	@echo "Targets:"
	@awk '\
	/^[[:space:]]*#[[:space:]]/ { \
		description = $$0; \
		sub(/^[[:space:]]*#[[:space:]]*/, "", description); \
		next; \
	} \
	/^[a-zA-Z0-9_-]+:/ { \
		target = $$0; \
		sub(/:.*/, "", target); \
		printf "  %-15s %s\n", target, description; \
		description = ""; \
		next; \
	} \
	{ description = "" }' [Mm]akefile

# Run syntax checks, tests, compilation, and cleanup.
all: check test compile
	$(MAKE) clean

# Check Lisp syntax.
check:
	$(EMACS) --batch -Q --eval '(with-temp-buffer (insert-file-contents "$(ELISP)") (check-parens))'

# Run the ERT test suite.
test:
	$(EMACS) --batch -Q -L lisp -L tests $(EMACS_LOAD_PATH_ARGS) -l gptel-commit-msg-test -f ert-run-tests-batch-and-exit

# Byte-compile the package.
compile:
	$(EMACS) --batch -Q -L lisp $(EMACS_LOAD_PATH_ARGS) -f batch-byte-compile $(ELISP)

# Remove generated bytecode.
clean:
	rm -f lisp/*.elc
